changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: New features 🎉
      labels:
        - enhancement
    - title: Breaking changes ⚠️
      labels:
        - breaking
    - title: Bugfixes 🐛
      labels:
        - bug
    - title: Other Changes 
      labels:
        - "*"
